export const FETCH_FAIL_MESSAGE = 'SERVER CONNECTION LOST';
export const NO_SEARCH_RESULTS_MESSAGE = 'NO MATCHES';
export const NO_FAVORITES_MESSAGE = 'MARK BEERS AS "Favorite" AND THEY WILL APPEAR HERE';
