export const actionTypes = {
    REQUEST_BEERS: "REQUEST_BEERS",
    BEERS_FETCHED: "BEERS_FETCHED",
    FETCH_BEERS_FAILED: "FETCH_BEERS_FAILED",
    RESET_BEERS: "RESET_BEERS",

    SET_REQUEST: "SET_REQUEST",

    FAVORITE_ADDED: "FAVORITE_ADDED",
    FAVORITE_REMOVED: "FAVORITE_REMOVED"
}

