export const actionTypes = {
    FETCH_FAVORITE_BEERS: "FETCH_FAVORITE_BEERS",
    FAVORITE_BEERS_FETCH_SUCCEEDED: "FAVORITE_BEERS_FETCH_SUCCEEDED",
    FAVORITE_BEERS_FETCH_FAILED: "FAVORITE_BEERS_FETCH_FAILED",
    SET_FAVORITES_REQUEST: "SET_FAVORITES_REQUEST",

    FETCH_LANDING_BEERS: "FETCH_LANDING_BEERS",
    FETCH_MORE_LANDING_BEERS: "FETCH_MORE_LANDING_BEERS",
    LANDING_BEERS_FETCH_SUCCEEDED: "LANDING_BEERS_FETCH_SUCCEEDED",
    LANDING_BEERS_FETCH_FAILED: "LANDING_BEERS_FETCH_FAILED",
    SEARCH_STARTED: "SEARCH_STARTED",

    FAVORITES_CHANGED: "FAVORITES_CHANGED"
}

