export const actionTypes = {
    REQUEST_FAVORITES_BEERS: "REQUEST_FAVORITES_BEERS",
    FAVORITES_BEERS_FETCHED: "FAVORITES_BEERS_FETCHED",
    FAVORITES_BEERS_FETCH_FAILED: "FAVORITES_BEERS_FETCH_FAILED",

    REQUEST_LANDING_BEERS: "REQUEST_LANDING_BEERS",
    REQUEST_MORE_LANDING_BEERS: "REQUEST_MORE_LANDING_BEERS",
    LANDING_BEERS_FETCHED: "LANDING_BEERS_FETCHED",
    LANDING_BEERS_FETCH_FAILED: "LANDING_BEERS_FETCH_FAILED",

    SEARCH_STARTED: "SEARCH_STARTED",

    SET_FAVORITES_REQUEST: "SET_FAVORITES_REQUEST",

    FAVORITES_CHANGED: "FAVORITES_CHANGED"
}

