// <auto-generated />
using BeerApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BeerApp.DataAccess.Migrations
{
    [DbContext(typeof(BeerCatalogContext))]
    [Migration("20180410105714_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("BeerApp.DataAccess.Models.Beer", b =>
                {
                    b.Property<long>("BeerId")
                        .ValueGeneratedOnAdd();

                    b.HasKey("BeerId");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("BeerApp.DataAccess.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ProfilePictureUrl");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BeerApp.DataAccess.Models.UserFavoriteBeer", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("BeerId");

                    b.HasKey("UserId", "BeerId");

                    b.HasIndex("BeerId");

                    b.ToTable("UserFavoriteBeers");
                });

            modelBuilder.Entity("BeerApp.DataAccess.Models.UserFavoriteBeer", b =>
                {
                    b.HasOne("BeerApp.DataAccess.Models.Beer", "Beer")
                        .WithMany("UserFavoriteBeers")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BeerApp.DataAccess.Models.User", "User")
                        .WithMany("UserFavoriteBeers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
