export const actionTypes = {
    FETCH_FAVORITE_BEERS: 'FETCH_FAVORITE_BEERS',
    FAVORITE_BEERS_FETCH_SUCCEEDED: 'FAVORITE_BEERS_FETCH_SUCCEEDED',
    FAVORITE_BEERS_FETCH_FAILED: 'FAVORITE_BEERS_FETCH_FAILED',

    SEARCH_STARTED: 'SEARCH_STARTED',
    FETCH_LANDING_BEERS: 'FETCH_LANDING_BEERS',
    LANDING_BEERS_FETCH_SUCCEEDED: 'LANDING_BEERS_FETCH_SUCCEEDED',
    LANDING_BEERS_FETCH_FAILED: 'LANDING_BEERS_FETCH_FAILED',

    FAVORITES_CHANGED: 'FAVORITES_CHANGED',

    SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
    SIGN_IN_SUCCEEDED: 'SIGN_IN_SUCCEEDED',
    SIGN_IN_FAILED: 'SIGN_IN_FAILED',

    SIGN_OUT: 'SIGN_OUT',

    CLEAR_ERRORS: 'CLEAR_ERRORS'
};
